version: "3.5"
services:
  web:
    image: partiks/sample_web:v2.01
    build: ./web
    hostname: sample_web
    container_name: sample_web
    restart: unless-stopped
    ports:
    - 8080:80
    environment:
    - "TZ=America/Chicago"

  backend:
    image: partiks/sample_backend:v2.01
    build: ./backend
    hostname: sample_backend
    container_name: sample_backend
    restart: unless-stopped
    #    ports:
    #     - 127.0.0.1:3000:3000
    environment:
    - "TZ=America/Chicago"
