version: "3.5"
services:
  web:
    image: partiks/sample_web:v1
    build: ./web
    hostname: sample_web
    container_name: sample_web
    restart: unless-stopped
    ports:
    - 8080:80
    environment:
    - "TZ=America/Chicago"
    depends_on:
    - backend

  backend:
    image: partiks/sample_backend:v1
    build: ./backend
    hostname: sample_backend
    container_name: sample_backend
    restart: unless-stopped
    ports:
    - 3000:3000
    environment:
    - "TZ=America/Chicago"
    depends_on:
    - db

  db:
    image: partiks/sample_mongo:v1
    build: ./db
    hostname: sample_mongo
    container_name: sample_mongo
    restart: unless-stopped
    ports:
    - 27017-27019:27017-27019
    environment:
    - "MONGO_INITDB_ROOT_USERNAME=admin"
    - "MONGO_INITDB_ROOT_PASSWORD=123"
    - "MONGO_INITDB_DATABASE=partiks_db" 
    - "TZ=America/Chicago"
      #    volumes:
      #    - ${PWD}/db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
      #    - ${PWD}/db/insert-data.js:/docker-entrypoint-initdb.d/insert-data.js
